### ISSUE TITLE
Setup first screen

### ISSUE THREAD

**Issue by steffi-s** [steffi-s/calculate_shapes_app#1]
## Situation

The app has currently one screen with a FAB and a text widget. All this should be removed.

## Goal

The app should show the first screen of the app with a basic greeting and a select field to choose a shape.

## Tasks

- [x] remove obsolete code in main.dart and delete the test file
- [x] create a text widget to greet users
- [x] create a select field to choose a shape
- [x] the app should not have an app-bar
- [x] show the user's choice as text beneath the select field for now
- [x] replace the text with a submit button

## Done

This issue is finished when users are properly greeted, and their choice is displayed beneath the select field.
