### ISSUE TITLE
Setup second screen

### ISSUE THREAD

**Issue by steffi-s** [steffi-s/calculate_shapes_app#2]
## Situation

The work on the first screen is now finished. Now users should be able to move on to the calculation screen, where they can type in values, so that the area and circumference of their selected shape can be calculated.

## Goal

Users can calculate the area and circumference of their selected shape.

## Tasks

- [x] create the 2nd screen with a title and input fields for numbers according to the user's choice
- [x] the input fields should correctly labelled according to the user's selection
- [x] users should be able to calculate the area of a shape
- [x] users should be able to calculate the circumference of a shape
- [x] users should be able to calculate the area and the circumference separately or at the same time
- [x] print the calculation results to the console for now

## Done

The screen shows the correct input(s) for the user's selected shape, and the calculation works as expected.
