### ISSUE TITLE
Setup third screen

### ISSUE THREAD

**Issue by steffi-s** [steffi-s/calculate_shapes_app#3]
## Situation

The calculation is complete, but users see no results. This is about to change.

## Goal

Users should see their calculation results on a new screen.

## Tasks

- [x] create the 3rd screen with a title and the results
- [x] the results should be displayed in a nice way
- [x] the screen should show as many results as there are calculations made (max. 2)
- [x] Allow users to move back to the starting screen

## Done

The screen has a proper title. Users see their results on a new screen, and they can move back to the second screen.
