### ISSUE TITLE
Create Models for Shapes

### ISSUE THREAD

**Issue by steffi-s** [steffi-s/calculate_shapes_app#5]
## Situation

The app has no way to calculate areas or circumferences for shape, because there are no models yet.

## Goal

Supported shapes should live in their own class, to  minimize hard coded strings or numbers. The app can differentiate between shapes and make calculations for the selected one.

## Tasks

- [x] create the base model
- [x] create a model for rectangle
- [x] create a model for circle
- [x] write unit test for the calculation methods

## Done

The calculations work correctly and all tests pass.
