### ISSUE TITLE
Refactoring Calculation Screen

### ISSUE THREAD

**Issue by steffi-s** [steffi-s/calculate_shapes_app#9]
## Situation

The calculation screen is currently pretty big and has redundant widgets., like controllers for text editing. The build has deep nesting of more than 5! levels.

## Tasks

Break the build tree into small widgets. Move them into their own methods or classes. Re-usable widgets should live in their own directory and class.

## Action

- [ ] break the tree into smaller items
- [ ] write own classes for widgets, that are used more than once
- [ ] finish the documentation: all changes made should be reflected in doc comments

## Result

The build tree is more concise, smaller, lighter and more readable. Re-usable widgets reduce redundancy.
